### ISSUE TITLE
angular client can't get past CORS restriction on local Swagger server

### ISSUE THREAD

**Issue by gpolyn** [neo4j-examples/neo4j-movies-template#17]
Hey, I get this error when pointing the Angular client to a local instance of the SwaggerUI

![screen shot 2015-02-25 at 7 29 48 pm](https://cloud.githubusercontent.com/assets/744660/6384013/e273bdba-bd24-11e4-8b77-8e0713e58192.png)

**Comment by whatSocks** [comment]
issue out of date, @gpolyn if you want to try again please go ahead.
