### ISSUE TITLE
graphDB upgrade

### ISSUE THREAD

**Issue by Ilona21** [neo4j-examples/neo4j-movies-template#20]
Hi, I got to the step of wanting to open the moviesDB with Neo, but it tells me: please set configuration parameter "allow_store_upgrade=true". 

I already have this flag to true, so I was wondering if you could just provide an upgraded moviesDB for Neo 2.3.0. It would be nice...

**Comment by Ilona21** [comment]
And now it stays in the yellow zone hanging... no message anymore, but not running either.

**Comment by cheerfulstoic** [comment]
The DB should be upgraded, but I think you can load it from any instance of Neo4j by running `:play movies` in the web console.  That will give you a query that you can click to load the data

**Comment by Ilona21** [comment]
It worked, thank you!
