### ISSUE TITLE
Content at PORT 3000 failed to load

### ISSUE THREAD

**Issue by Ilona21** [neo4j-examples/neo4j-movies-template#21]
After having failed to get this example to speak on windows 10 (as bootstrap was not compatible with it) I decided to give it a try on a Ubuntu14 VM. 
Somehow I got to the end (I had problems with the middleware,  but I I think I installed all the necessary npm modules and that this is fine now).
So finally I got to the point where the system listens on port 3000, and I actually see all the GETS. But when I look for content it is EMPTY. 

Also on port 5000 I can see the frame, but not content.

What do you think the problem is? What can I do?

**Comment by whatSocks** [comment]
@Ilona21 closing this issue as it's now out of date. Please let me know if it still fails.
