### ISSUE TITLE
This application example is broken !

### ISSUE THREAD

**Issue by AaronNGray** [neo4j-examples/neo4j-movies-template#22]
This application example is broken !
And the demo is broken too !
Please fix !

**Comment by cheerfulstoic** [comment]
I'm not the maintainer here, but I imagine that an example of the problem that you're having would be useful to getting it fixed

**Comment by jexp** [comment]
Please report the detailed error that happens in local deployment.

I pushed a 2.3 version of the database zip that should help you locally.
We're gonna fix the online demo in the next days.

**Comment by jexp** [comment]
Hi @AaronNGray sorry this work has to be updated, it's on the plan but won't be possible to be fixed soon.

**Comment by biswatmanayak** [comment]
Guys please update the README files and fix the broken issue, there is no good tutorial/example app based on node js

**Comment by whatSocks** [comment]
issue out of date
