### ISSUE TITLE
updated for Neo4j 3.0.3

### ISSUE THREAD

**Issue by scottcsims** [neo4j-examples/neo4j-movies-template#25]
Can this project be updated for Neo4j 3.0.3?  Also it would be good to have TDD examples include in the template.

**Comment by whatSocks** [comment]
Yes, staying current on Neo4j version, adding tests, and using the new javascript driver are on the roadmap

**Comment by whatSocks** [comment]
Hi, 
I just tested it on a fresh download of Neo4j 3.0.3 (the .dmg version that comes with the GUI) and noticed there was a bug on the `neo4j-import`. I updated the readme with the bandaid solution:

```
java -cp /Applications/Neo4j\ Community\ Edition.app/Contents/Resources/app/bin/neo4j-desktop-3.0.3.jar org.neo4j.tooling.ImportTool --into database/ --nodes:Person csv/person_node.csv --nodes:Movie csv/movie_node.csv --nodes:Genre csv/genre_node.csv --nodes:Keyword csv/keyword_node.csv --relationships:ACTED_IN csv/acted_in_rels.csv --relationships:DIRECTED csv/directed_rels.csv --relationships:HAS_GENRE csv/has_genre_rels.csv --relationships:HAS_KEYWORD csv/has_keyword_rels.csv --relationships:PRODUCED csv/produced_rels.csv --relationships:WRITER_OF csv/writer_of_rels.csv --delimiter ";" --array-delimiter "|" --id-type INTEGER
```

**Comment by biswatmanayak** [comment]
does that import command works on windows platform ?
 `java -cp /Applications/Neo4j\ Community\ Edition.app/Contents/Resources/app/bin/neo4j-desktop-3.0.3.jar org.neo4j.tooling.ImportTool --into database/ --nodes:Person csv/person_node.csv --nodes:Movie csv/movie_node.csv --nodes:Genre csv/genre_node.csv --nodes:Keyword csv/keyword_node.csv --relationships:ACTED_IN csv/acted_in_rels.csv --relationships:DIRECTED csv/directed_rels.csv --relationships:HAS_GENRE csv/has_genre_rels.csv --relationships:HAS_KEYWORD csv/has_keyword_rels.csv --relationships:PRODUCED csv/produced_rels.csv --relationships:WRITER_OF csv/writer_of_rels.csv --delimiter ";" --array-delimiter "|" --id-type INTEGER`

**Comment by whatSocks** [comment]
@biswatmanayak find your OS [here](https://gist.github.com/jexp/4692ad9cd14b6d9c1cc8bffa079c98fa) and try it, replacing `"$@"` or `%*` with 

```
--into database/ --nodes:Person csv/person_node.csv --nodes:Movie csv/movie_node.csv --nodes:Genre csv/genre_node.csv --nodes:Keyword csv/keyword_node.csv --relationships:ACTED_IN csv/acted_in_rels.csv --relationships:DIRECTED csv/directed_rels.csv --relationships:HAS_GENRE csv/has_genre_rels.csv --relationships:HAS_KEYWORD csv/has_keyword_rels.csv --relationships:PRODUCED csv/produced_rels.csv --relationships:WRITER_OF csv/writer_of_rels.csv --delimiter ";" --array-delimiter "|" --id-type INTEGER
```

https://gist.github.com/jexp/4692ad9cd14b6d9c1cc8bffa079c98fa

you'll have to update the neo4j version in the snippet with whatever you're using
