### ISSUE TITLE
{ code: 404, reason: 'genres not found' }

### ISSUE THREAD

**Issue by biswatmanayak** [neo4j-examples/neo4j-movies-template#26]
`{ [Error: [object Object]]
  stack: [Getter/Setter],
  message: { errors: [ [Object] ] },
  __frame:
   { name: 'GraphDatabase_prototype_query__20',
     line: 710,
     file: 'lib/GraphDatabase._coffee',
     prev: undefined,
     calls: 1,
     active: false,
     offset: 2,
     col: 24 },
  rawStack: [Getter] }
{ code: 404, reason: 'genres not found' }

D:\Biswatma\neo4j\neo4j-movies-template-master\api\routes\genres.js:54
        if (err || !response.results) throw swe.notFound("genres"); `

I am getting this error while accessing api .

**Comment by whatSocks** [comment]
Hello, I updated the example code and readme to fix a typo causing this issue. 

pull and update `api/config.js` with your username and pw and see if it works.

**Comment by whatSocks** [comment]
Hello, 
I made some video instructions here https://www.youtube.com/edit?video_id=O71B2KcTD6A
