### ISSUE TITLE
The Frontend pages has nothing, only 'Featured Movies'

### ISSUE THREAD

**Issue by hyndaniel** [neo4j-examples/neo4j-movies-template#27]
I deployed all of this project, the api link localhost:3000 is right and has many GET requests, but the Frontend page has nothing , only a big size and bold 'Featured Movies', such as #Featured Movies# , and on this page, the F12--console has nothing red (WARN or ERROR) . PLEASE HELP ME!

**Comment by whatSocks** [comment]
Hello, what operating system are you using? Can you see and use the swagger when you build the api?

**Comment by hyndaniel** [comment]
system is Centos6.5
Does there has anything wrong?  Sorry about that, I didn't know much about Swagger
![image](https://cloud.githubusercontent.com/assets/18070336/17129607/b336e8ec-5346-11e6-8701-38bfdcdd4257.png)
and the Frontend page is 


thanks

**Comment by hyndaniel** [comment]
the Frontend page is 
![image](https://cloud.githubusercontent.com/assets/18070336/17130389/d59820fa-534a-11e6-8f75-345df11d1fd3.png)

**Comment by whatSocks** [comment]
What happens when you click on one `/genres` in swagger? Do you have a database running locally? You should be able to see it at localhost:7474

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!

**Comment by hyndaniel** [comment]
I reset the database just now, and the all things are running !
thanks a lot!
