### ISSUE TITLE
Css was not created by the application in build

### ISSUE THREAD

**Issue by lucasjovencio** [neo4j-examples/neo4j-movies-template#38]
> [17:39:26] STYLES ERROR: { [Error: src/styles/main.scss
Error: File to import not found or unreadable: ../../bower_components/foundation/scss/normalize
       Parent style sheet: stdin
        on line 2 of stdin
>> @import '../../bower_components/foundation/scss/normalize';
   ^
]
  status: 1,
  file: 'stdin',
  line: 2,
  column: 1,
  message: 'src/styles/main.scss\nError: File to import not found or unreadable: ../../bower_components/foundation/scss/normalize\n       Parent style sheet: stdin\n        on line 2 of stdin\n>> @import \'../../bower_components/foundation/scss/normalize\';\n   ^\n',
  formatted: 'Error: File to import not found or unreadable: ../../bower_components/foundation/scss/normalize\n       Parent style sheet: stdin\n        on line 2 of stdin\n>> @import \'../../bower_components/foundation/scss/normalize\';\n   ^\n',
  messageFormatted: '\u001b[4msrc/styles/main.scss\u001b[24m\nError: File to import not found or unreadable: ../../bower_components/foundation/scss/normalize\n       Parent style sheet: stdin\n        on line 2 of stdin\n>> @import \'../../bower_components/foundation/scss/normalize\';\n   ^\n',
  name: 'Error',
  stack: 'Error: src/styles/main.scss\nError: File to import not found or unreadable: ../../bower_components/foundation/scss/normalize\n       Parent style sheet: stdin\n        on line 2 of stdin\n>> @import \'../../bower_components/foundation/scss/normalize\';\n   ^\n\n    at options.error (/home/ubuntu/Documents/neo4j-movies-template-master/web/node_modules/node-sass/lib/index.js:286:26)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-sass' }

#

![css](https://cloud.githubusercontent.com/assets/16108908/22481650/2ba2cb9a-e7dd-11e6-90f3-ac095b41cd8a.png)

**Comment by whatSocks** [comment]
try deleting the `node_modules` and re-installing them.

**Comment by lucasjovencio** [comment]
Okay, I try.

**Comment by lucasjovencio** [comment]
I solved. Deleting the dependencies node_modules and reinstalling. I also ran the command: bower install foundation-sites --save for update the corrupted dependency. Thanks.
